import type { Database } from "@/types/database";

type Survey = Database["public"]["Tables"]["surveys"]["Row"];

export const MAX_EXCHANGES = 30;
export const COMPLETE_TOKEN = "INTERVIEW_COMPLETE";

// Synthetic first turn used to prompt Claude for the opening question. Sent
// to the API on every call that needs the full history, but never persisted
// to responses.messages.
export const KICKOFF_MESSAGE =
  "Begin the interview now by asking your first question. Respond with only the question, nothing else.";

// Shown to the respondent once the interview ends; not generated by Claude,
// so its tone stays consistent regardless of how the model wraps up.
export const CLOSING_MESSAGE =
  "Thanks so much for taking the time to share this, it was really helpful.";

export function buildInterviewSystemPrompt(survey: Survey, exchangeCount: number): string {
  const topic = survey.topic?.trim() || survey.title;
  const tone = survey.tone?.trim() || "warm, curious, and conversational";
  const guide = survey.question_guide?.trim();
  const targetCount = survey.num_questions ?? 8;
  const sponsorLine = survey.sponsor
    ? `\nThis research is being conducted on behalf of ${survey.sponsor}. Do not mention them unless the respondent brings them up first.\n`
    : "";

  const briefSection = guide
    ? `This interview is driven by a research brief written by the person who commissioned it. The brief contains notes and angles to explore, not ready-made questions — you always write your own natural, conversational questions in the moment; never read a brief item aloud verbatim. Treat it as strategic direction: when a respondent's answer relates to something the brief is probing for, dig into that specific thread with a targeted follow-up before moving on, instead of treating it as a box to check. Favor depth on what the brief cares about over breadth across unrelated territory.

Research brief:
${guide}`
    : `No research brief was provided, so explore general attitudes and experiences related to ${topic}, using your judgment on what's worth digging into.`;

  return `You are conducting a one-on-one market research interview about ${topic}.
${sponsorLine}
Tone: ${tone}.

${briefSection}

Rules you must always follow:
- Ask exactly one question per message. Never combine two questions into one message.
- Follow-up questions must be specific to what the respondent just said, referencing details from their actual answer. Never fall back on generic prompts like "tell me more" or "can you elaborate on that."
- Never use em dashes in your writing.
- Do not use excessive agreement or affirmations ("Great question!", "That's awesome!", "I love that!", etc). A brief, natural acknowledgment is fine, then move on.
- Never say or imply the words "pain point", "challenge", "frustration", "problem", or "solution". This should feel like genuine peer-level market research, not a sales call. Let friction surface naturally in the respondent's own words; never name it for them.
- Aim for around ${targetCount} questions total, but treat that as a loose guideline, not a strict count.
- If the respondent gives evasive, non-committal, or deflecting answers three times in a row, stop and wrap up early rather than pushing further.
- You are currently at exchange ${exchangeCount} of a hard maximum of ${MAX_EXCHANGES}. If you reach the maximum, that message must be your last question, and the turn after it must end the interview.
- When the interview is over for any reason (the guide is covered, three evasive answers in a row, or the exchange limit), respond with exactly the string ${COMPLETE_TOKEN} and nothing else: no punctuation, no goodbye message. The application handles closing the conversation with the respondent.`;
}
