import type { Database } from "@/types/database";
import {
  parseEnabledRespondentFields,
  parseCustomRespondentFieldDefs,
  parsePresetFieldLabel,
} from "@/lib/surveys/respondent-fields";

// RESPONDENT-FACING COPY RULE: never mention or deny sales intent.
// No "sales", "pitch", "leads", "not a sales call", etc. Also never claim
// their info is "only" used for X, or make any exclusive-use / "never
// shared" claim — state true things we WILL do, don't enumerate or limit
// what else happens.

type Survey = Database["public"]["Tables"]["surveys"]["Row"];

export const MAX_EXCHANGES = 30;
export const COMPLETE_TOKEN = "INTERVIEW_COMPLETE";

// Throughout the prompt, "exchange" means exactly one thing: one question
// from Claude plus the respondent's answer to it. It is never used for
// messages.length, which runs at ~2x the respondent's actual turn count
// because it includes Claude's own messages.

/** What a survey with no num_questions set gets. */
export const DEFAULT_QUESTION_COUNT = 8;

/**
 * The interview's length, in questions, follow-ups included.
 *
 * This is a hard total, not a topic target. It used to be the number of
 * topics, with the interviewer allowed one follow-up per topic, so an
 * interview promised as "8 questions" could legitimately run to 16 while
 * the respondent's counter sat at "8 of 8" for the second half. The number
 * the admin sets, the number the welcome screen promises, the counter the
 * respondent watches and the point at which the server stops asking are now
 * all this one value. The continue route enforces it; the prompt paces
 * against it.
 */
export function questionBudgetFor(numQuestions: number | null | undefined): number {
  const requested = numQuestions ?? DEFAULT_QUESTION_COUNT;
  return Math.min(Math.max(1, Math.round(requested)), MAX_EXCHANGES);
}

// Synthetic first turn used to prompt Claude for the opening question. Sent
// to the API on every call that needs the full history, but never persisted
// to responses.messages.
export const KICKOFF_MESSAGE =
  "Begin the interview now by asking your first question. Respond with only the question, nothing else.";

// Shown to the respondent once the interview ends; not generated by Claude,
// so its tone stays consistent regardless of how the model wraps up.
export const CLOSING_MESSAGE =
  "Thanks so much for taking the time to share this, it was really helpful.";

export type InterviewCompanyProfile = {
  whatWeSell: string | null;
  targetIcp: string | null;
  valueProp: string | null;
};

export type InterviewRespondent = {
  name: string | null;
  customFieldValues: Record<string, unknown> | null;
};

// Used only by the start route: turns the generic kickoff instruction into
// one that asks Claude to open with a brief greeting using the respondent's
// first name and, if known, their role or company — folded into the same
// user-turn message that requests the opening question, rather than a
// standing system-prompt rule (which would linger, contextually stale,
// through the rest of the conversation after the opening message).
export function buildKickoffMessage(respondent?: InterviewRespondent | null): string {
  const firstName = firstNameOf(respondent?.name);
  const values = respondent?.customFieldValues ?? {};
  const role = typeof values.job_title === "string" ? values.job_title.trim() : "";
  const company = companyOf(values);

  if (!firstName && !role && !company) return KICKOFF_MESSAGE;

  const who = [
    firstName ? `their name is ${firstName}` : null,
    role ? `their role is ${role}` : null,
    company ? `they're at ${company}` : null,
  ]
    .filter(Boolean)
    .join(", ");

  return `Begin the interview now. Open with a brief, natural one-sentence greeting — ${who} — then ask your first question in the same message. Respond with only the greeting and the question, nothing else.`;
}

function firstNameOf(name: string | null | undefined): string | null {
  const trimmed = name?.trim();
  if (!trimmed) return null;
  return trimmed.split(/\s+/)[0];
}

// An explicit "company" field (surveys that kept it after the preset was
// removed going forward) always wins over the derived-from-email-domain
// name, matching the same explicit-else-derived preference the admin leads
// queue and response detail view use.
function companyOf(values: Record<string, unknown>): string {
  const explicit = typeof values.company === "string" ? values.company.trim() : "";
  if (explicit) return explicit;
  const derived = typeof values.derived_company_name === "string" ? values.derived_company_name.trim() : "";
  return derived;
}

// Resolves the respondent's raw custom_field_values against the survey's
// own field definitions (surveys.custom_fields) so preset keys like
// "job_title" and admin-defined custom keys like "custom_team_size" both
// render with their real, human-readable labels rather than raw keys.
function describeRespondentContext(survey: Survey, respondent?: InterviewRespondent | null): string {
  if (!respondent) return "";

  const firstName = firstNameOf(respondent.name);
  const values = respondent.customFieldValues ?? {};

  const enabledPresets = parseEnabledRespondentFields(survey.custom_fields);
  const customDefs = parseCustomRespondentFieldDefs(survey.custom_fields);

  const details: string[] = [];
  for (const key of enabledPresets) {
    // Company is handled separately below so it can fall back to the
    // email-derived name on surveys that don't collect it explicitly.
    if (key === "company") continue;
    const raw = values[key];
    if (typeof raw === "string" && raw.trim()) {
      details.push(`${parsePresetFieldLabel(survey.custom_fields, key)}: ${raw.trim()}`);
    }
  }
  for (const def of customDefs) {
    const raw = values[def.key];
    if (typeof raw === "string" && raw.trim()) {
      details.push(`${def.label}: ${raw.trim()}`);
    }
  }
  const company = companyOf(values);
  if (company) {
    const companyLabel = enabledPresets.includes("company")
      ? parsePresetFieldLabel(survey.custom_fields, "company")
      : "Company";
    details.push(`${companyLabel}: ${company}`);
  }

  if (!firstName && details.length === 0) return "";

  const lines: string[] = [];
  if (firstName) {
    lines.push(
      `The respondent's first name is ${firstName}. Address them by name naturally where it fits, not in every message.`
    );
  }
  if (details.length > 0) {
    lines.push(
      `You also know this about them: ${details.join(", ")}. Weave these in naturally where relevant instead of listing them back at the respondent.`
    );
  }
  return `\n${lines.join("\n")}\n`;
}

export function buildInterviewSystemPrompt({
  survey,
  companyProfile,
  respondent,
  exchangeCount,
}: {
  survey: Survey;
  companyProfile?: InterviewCompanyProfile | null;
  respondent?: InterviewRespondent | null;
  /**
   * Exchanges completed so far, i.e. the respondent's answered-turn count.
   * The only progress counter the prompt gets: it drives the "N of total"
   * line, and the continue route's hard stop reads the same number, so the
   * two can never disagree.
   */
  exchangeCount: number;
}): string {
  const topic = survey.topic?.trim() || survey.title;
  const tone = survey.tone?.trim() || "warm, curious, and conversational";
  const guide = survey.question_guide?.trim();
  const targetCount = questionBudgetFor(survey.num_questions);
  const remaining = Math.max(0, targetCount - exchangeCount);
  const sponsorLine = survey.sponsor
    ? `\nThis research is being conducted on behalf of ${survey.sponsor}. Do not mention them unless the respondent brings them up first.\n`
    : "";

  const briefSection = guide
    ? `This interview is driven by a research brief written by the person who commissioned it. The brief contains notes and angles to explore, not ready-made questions — you always write your own natural, conversational questions in the moment; never read a brief item aloud verbatim. Treat it as strategic direction: when a respondent's answer relates to something the brief is probing for, dig into that specific thread with a targeted follow-up before moving on, instead of treating it as a box to check. Favor depth on what the brief cares about over breadth across unrelated territory.

Research brief:
${guide}`
    : `No research brief was provided, so explore general attitudes and experiences related to ${topic}, using your judgment on what's worth digging into.`;

  const profileParts: string[] = [];
  if (companyProfile?.whatWeSell) profileParts.push(`sells: ${companyProfile.whatWeSell}`);
  if (companyProfile?.targetIcp) profileParts.push(`targets customers like: ${companyProfile.targetIcp}`);
  if (companyProfile?.valueProp) profileParts.push(`value proposition: ${companyProfile.valueProp}`);

  const profileSection =
    profileParts.length > 0
      ? `\nThe company running this research ${profileParts.join("; ")}. Treat this strictly as topic areas to naturally gravitate follow-up questions toward — never mention the sponsor's product, never pitch, never hint that these topics are of commercial interest. Use it to decide which topics are actually worth your limited questions: prioritize the parts of the respondent's workflow or experience that plausibly connect to this. If the respondent opens up a genuinely interesting tangent that isn't connected to it, you can follow it briefly, but don't let it eat the interview; return to and make sure you cover the core territory described above before wrapping up. Never mention the company by name.\n`
      : "";

  const respondentSection = describeRespondentContext(survey, respondent);

  return `You are conducting a one-on-one market research interview about ${topic}.
${sponsorLine}
Tone: ${tone}.

${briefSection}
${profileSection}${respondentSection}
Rules you must always follow:
- Ask exactly one question per message. Never combine two questions into one message.
- Every single message you send must bold one short phrase using standard markdown (double asterisks), no exceptions. This applies to every message in the interview, not just some of them: the opening question, every follow-up, all of it. Bold the specific term or phrase the question is actually about, short enough that reading just the bolded words alone tells you what's being asked. Never a single word, never the whole sentence, and never more than one bolded phrase per message. For example: "That's a notable workaround, keeping two dispatchers on weekends specifically because of after-hours call volume. Can you tell me more about **how you currently route** emergency calls when the office is closed, what does that look like outside the scheduling board?"
- Follow-up questions must be specific to what the respondent just said, referencing details from their actual answer. Never fall back on generic prompts like "tell me more" or "can you elaborate on that."
- Never use em dashes in your writing.
- Do not use excessive agreement or affirmations ("Great question!", "That's awesome!", "I love that!", etc). A brief, natural acknowledgment is fine, then move on.
- Occasionally, not as a habit, nod to what they just said before asking the next question. Aim for roughly one message in three, weighted toward the first half of the interview (around the first ${Math.ceil(targetCount / 2)} topics) and tapering off to almost none by the end. Keep it to a short clause, never a sentence of its own, and keep it plain and observational, the way a real interviewer briefly registers an answer before moving on: "yeah, that comes up a lot", "okay, so still mostly manual then", "that's a pretty common setup". No superlatives, no exclamation points, and nothing in the register of "great", "love that", "totally", or "absolutely". This is about conversational flow only: never let the acknowledgment affirm or validate the substance of what they described, never treat any answer as more significant than another, and never suggest you are evaluating what they tell you.
- Never deliver a verdict on the respondent's answer. Two forms of this are banned, both anywhere in the message and not merely at the start. The blunt form: "Interesting", "Fascinating", "Makes sense", "Got it", "Wow", "Right", "Sure". The softer form, which is the one you will actually be tempted by: "That's helpful", "That's useful", "That's a good point", "That's a useful distinction", "That's notable", "good to hear", "worth digging into". Never use the words "interesting", "fascinating", "helpful", "useful", or "notable" to describe anything they have said, in any wording.
- Most of your messages should open directly with the question, no preamble at all. When you do lead with something first, it must be either a plain factual restatement of a specific detail they just gave or the brief acknowledgment described above, carrying no adjective of quality: "So the SLA came and went without ever really sticking." is fine; "That's a useful distinction." is not.
- Vary how you open, but never at the cost of sounding natural. You will drift toward starting message after message with "That" or "That's": do not open more than one message in a row that way. If the opener you are reaching for repeats the shape of the last one, drop the preamble entirely and go straight to the question, which is always a safe choice. Always speak to the respondent directly, in the second person: never refer to them by name in the third person or narrate what they said as though describing them to someone else.
- Never say or imply the words "pain point", "challenge", "frustration", "problem", or "solution". This should feel like genuine peer-level market research. Let friction surface naturally in the respondent's own words; never name it for them.
- Never say or imply the words "sales", "selling", "pitch", "lead", or "pipeline", and never describe the conversation by what it is not (e.g. "not a sales call", "no strings attached"). If the respondent directly asks whether this is a sales call, a pitch, or connected to being sold something, do not answer with a denial: simply restate plainly what the conversation actually is (a short research conversation about ${topic}) and move the conversation forward with your next question.
- If it comes up naturally in the conversation, you can get curious about things like who else would be involved in a decision like this, what's actually driving them to think about it now, or what would matter most to them in picking something new. Only ask about this if it fits naturally where the conversation is already headed. Never ask more than one of these in a single interview, and never ask about the same thing twice in different words. If none of it comes up naturally, that's fine, don't force it. Keep the phrasing simple and conversational, the way a curious peer would ask it, not a business analyst.
- Never ask a question that substantively repeats one you already asked and got an answer to earlier in this interview, even if it's phrased differently. If you're tempted to revisit something, it means it's time to move to a new topic instead.
- After every question you ask, on its own line at the very end of the message, append a block in this exact form: ||CHIPS: option one | option two | option three|| containing 2-3 short, plausible answers to the question you just asked, as quick-reply shortcuts a respondent can tap instead of typing. The closing || is mandatory, not decoration: it is the only thing that tells the application where the block ends, and it must be the very last thing in your message, immediately after the final option, with nothing after it. Correct: ||CHIPS: mostly by phone and text | we use a shared spreadsheet | honestly kind of ad hoc||. Malformed, never do this — missing the closing ||: ||CHIPS: mostly by phone and text | we use a shared spreadsheet | honestly kind of ad hoc. If you find yourself running low on room to finish the message, shorten or drop an option rather than leaving the block unclosed. Phrase the options the way a real person would actually text them back: casual, lowercase-friendly, no full sentences, no form-option phrasing ("Option A", "Yes/No/Maybe"). They're optional shortcuts a respondent can tap and still edit, not a multiple-choice list, so your question itself must read exactly as natural on its own as if the block weren't there, never referencing or hinting that these shortcuts exist. Never include this block on the message where you respond with ${COMPLETE_TOKEN}.
- This interview is exactly ${targetCount} questions long, and a follow-up counts as one of them. The respondent sees a "question N of ${targetCount}" counter, so that total is a promise, not a guideline. An exchange is one question from you plus the respondent's answer to it. The respondent has answered ${exchangeCount} of ${targetCount} so far, so you have ${remaining} ${remaining === 1 ? "question" : "questions"} left, and the next one you ask is question ${Math.min(exchangeCount + 1, targetCount)} of ${targetCount}.
- Spend that budget deliberately. A targeted follow-up on a thread the brief cares about is worth one of the ${targetCount}; a follow-up on a tangent is not. Never drill three or four layers deep into one thread, and make sure the brief's most important threads are reached before the budget runs out: when you have only two or three questions left, open no new territory that cannot be closed in one question.
- If the respondent gives evasive, non-committal, or deflecting answers three times in a row, stop and wrap up early rather than pushing further.
- When the respondent has answered question ${targetCount} of ${targetCount}, the interview is over: do not ask anything further. Respond with exactly the string ${COMPLETE_TOKEN} and nothing else. The same applies when the interview ends early for three evasive answers in a row. No punctuation, no goodbye message: the application handles closing the conversation with the respondent.`;
}
